name: Deploy FastAPI to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-and-deploy:
    name: Build & Deploy (main)
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Ensure LFS files
        run: git lfs pull

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (clean)
        run: |
          python -m pip install -U pip wheel
          pip install --upgrade --no-cache-dir -r requirements.txt
          pip check || true   # évite l'échec dur si des warnings mineurs existent

      - name: Smoke tests
        run: |
          python - << 'PY'
          print("no tests – smoke ok")
          PY

      - name: Prepare package
        run: |
          mkdir -p artifact
          rsync -a \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '__pycache__' \
            --exclude '.pytest_cache' \
            --exclude 'artifact' \
            ./ artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: artifact

      - name: Download artifact (deploy step input)
        uses: actions/download-artifact@v4
        with:
          name: app-package
          path: .

      - name: Deploy to Azure WebApp
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: p7-sentiment-api
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: .
