name: Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # aligne avec ton env local

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # En cas d'absence de TF dans requirements, décommente la ligne suivante :
          # pip install "tensorflow-cpu>=2.15,<3.0"

      - name: Run tests
        env:
          PYTHONPATH: .
          TF_CPP_MIN_LOG_LEVEL: "2"
          MAX_LEN: "80"
        run: |
          pytest --maxfail=1 -q